require("plugins.packer")
require("plugins.lsp")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.git-blame")
require("plugins.copilot")
require("plugins.cmp")
require("plugins.symbols-outline")
require("plugins.chatgpt")
require("plugins.gitsigns")
require("plugins.diffview")

require("core.options")
require("core.keymaps")
