require("plugins.packer")
require("plugins.lsp")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.git-blame")

require("core.options")
require("core.keymaps")
